### ISSUE TITLE
ratingEmpty and ratingFilled doesnt work

### ISSUE THREAD

**Issue by kohry** [borjabravo10/SimpleRatingBar#2] opened 2017-03-15 13:57 UTC
ratingEmpty and ratingFilled doesnt work

**Comment by borjabravo10** [comment] 2017-03-22 19:35
hi @kohry can you tell me what is the problem? 
If I add ratingEmpty or ratingFilled property on xml, it's working perfectly
Close the issue, I cannot reproduce it.

**Closed by borjabravo10** 2017-03-22 19:35 UTC
